<?php
require("notazz-php.php");

$fields = json_encode(array(
    "API_KEY" => "SUA CHAVE DE API",
    "METHOD" => "create_nfe_55",
    "DESTINATION_NAME" => "Jose Maria da Silva",
    "DESTINATION_TAXID" => "35281474588",
    "DESTINATION_IE" => "12345678",
    "DESTINATION_IM" => "12345678",
    "DESTINATION_TAXTYPE" => "F",
    "DESTINATION_STREET" => "Rua de teste",
    "DESTINATION_NUMBER" => "123",
    "DESTINATION_COMPLEMENT" => "Apt. 101",
    "DESTINATION_DISTRICT" => "Centro",
    "DESTINATION_CITY" => "Belo Horizonte",
    "DESTINATION_UF" => "MG",
    "DESTINATION_ZIPCODE" => "31320240",
    "DESTINATION_PHONE" => "31999998888",
    "DESTINATION_EMAIL" => "test@test.com",
    "DESTINATION_EMAIL_SEND" => array(
        "1" => array(
            "EMAIL" => "mail1@example.com" 
        ),
        "2" => array(
            "EMAIL" => "mail2@example.com" 
        ),
    ),
    "DOCUMENT_BASEVALUE" => "100.00",
    "DOCUMENT_DESCRIPTION" => "DOCUMENTO EMITIDO POR ME OU EPP OPTANTE PELO SIMPLES NACIONAL",
    "DOCUMENT_CNAE" => "8599604",
    "DOCUMENT_GOAL" => "1",
    "DOCUMENT_PAYMENT_FORM_INDICATOR" => "0",
    "DOCUMENT_INTERMEDIARY_TAXID" => "0000000000000",
    "DOCUMENT_INTERMEDIARY_NAME" => "MARKETPLACE X",
    "DOCUMENT_OPERATION_TYPE" => "1",
    "DOCUMENT_REFERENCED" => "510807012123440001275500010000000981364117781",
    "DOCUMENT_NATURE_OPERATION" => "VENDA",
    "DOCUMENT_PRODUCT" => array(
        "1" => array(
            "DOCUMENT_PRODUCT_COD" => "1",
            "DOCUMENT_PRODUCT_TAX_COD" => "123",
            "DOCUMENT_PRODUCT_EAN" => "190520367911",
            "DOCUMENT_PRODUCT_NAME" => "Camisa Polo",
            "DOCUMENT_PRODUCT_QTD" => "2",
            "DOCUMENT_PRODUCT_UNITARY_VALUE" => "5.00",
            "DOCUMENT_PRODUCT_NCM" => "62069000",
            "DOCUMENT_PRODUCT_CEST" => "2805900",
            "DOCUMENT_PRODUCT_CFOP" => "5101",
            "DOCUMENT_PRODUCT_DISCOUNT" => "2.00",
            "DOCUMENT_PRODUCT_ICMS_CST" => "102",
            "DOCUMENT_PRODUCT_IPI_CST" => "99",
            "DOCUMENT_PRODUCT_PIS_CST" => "99",
            "DOCUMENT_PRODUCT_COFINS_CST" => "99",
            "DOCUMENT_PRODUCT_ICMS_ALIQUOTA" => "0.00",
            "DOCUMENT_PRODUCT_IPI_ALIQUOTA" => "0.00",
            "DOCUMENT_PRODUCT_PIS_ALIQUOTA" => "0.00",
            "DOCUMENT_PRODUCT_COFINS_ALIQUOTA" => "0.00",                       
            "DOCUMENT_PRODUCT_OTHER_EXPENSES" => "0.00",                       
        ),
        "2" => array(
            "DOCUMENT_PRODUCT_COD" => "2",
            "DOCUMENT_PRODUCT_TAX_COD" => "456",            
            "DOCUMENT_PRODUCT_EAN" => "0020970",
            "DOCUMENT_PRODUCT_NAME" => "Oculos Feminino",
            "DOCUMENT_PRODUCT_QTD" => "1",
            "DOCUMENT_PRODUCT_UNITARY_VALUE" => "90.00",
            "DOCUMENT_PRODUCT_NCM" => "62069000",
            "DOCUMENT_PRODUCT_CEST" => "2805900",            
            "DOCUMENT_PRODUCT_CFOP" => "5101",
            "DOCUMENT_PRODUCT_DISCOUNT" => "2.00",
            "DOCUMENT_PRODUCT_ICMS_CST" => "102",
            "DOCUMENT_PRODUCT_IPI_CST" => "99",
            "DOCUMENT_PRODUCT_PIS_CST" => "99",
            "DOCUMENT_PRODUCT_COFINS_CST" => "99",
            "DOCUMENT_PRODUCT_ICMS_ALIQUOTA" => "0.00",
            "DOCUMENT_PRODUCT_IPI_ALIQUOTA" => "0.00",
            "DOCUMENT_PRODUCT_PIS_ALIQUOTA" => "0.00",
            "DOCUMENT_PRODUCT_COFINS_ALIQUOTA" => "0.00",  
            "DOCUMENT_PRODUCT_OTHER_EXPENSES" => "0.00",                                 
        ),
    ),
    "DOCUMENT_DUPLICATE" => array(
        "1" => array(
            "DOCUMENT_DUPLICATE_COD" => "1",
            "DOCUMENT_DUPLICATE_DUE_DATE" => "2021-01-01",
            "DOCUMENT_DUPLICATE_VALUE" => "90.00",
        ),
        "2" => array(
            "DOCUMENT_DUPLICATE_COD" => "2",
            "DOCUMENT_DUPLICATE_DUE_DATE" => "2021-02-01",
            "DOCUMENT_DUPLICATE_VALUE" => "10.00",
        ),
    ),
    "DOCUMENT_FRETE" => array(
        "DOCUMENT_FRETE_MOD" => "0",
        "DOCUMENT_FRETE_VALUE" => "100.00",
        "DOCUMENT_FRETE_TRANSPORTADORA" => array(
            "DOCUMENT_FRETE_TRANSPORTADORA_NAME" => "Empresa Brasileira de Correios e Telégrafos",
            "DOCUMENT_FRETE_TRANSPORTADORA_TAXID" => "34028316002742",
            "DOCUMENT_FRETE_TRANSPORTADORA_IE" => "12345678",
            "DOCUMENT_FRETE_TRANSPORTADORA_STREET" => "Rua de teste",
            "DOCUMENT_FRETE_TRANSPORTADORA_NUMBER" => "123",
            "DOCUMENT_FRETE_TRANSPORTADORA_DISTRICT" => "Centro",
            "DOCUMENT_FRETE_TRANSPORTADORA_CITY" => "Belo Horizonte",
            "DOCUMENT_FRETE_TRANSPORTADORA_UF" => "MG",
        ),
        "DOCUMENT_FRETE_VEICULO" => array(
            "DOCUMENT_FRETE_VEICULO_PLACA" => "ZZZ1100",
            "DOCUMENT_FRETE_VEICULO_UF" => "MG",
        ),
        "DOCUMENT_FRETE_VOLUMES" => array(
            "DOCUMENT_FRETE_VOLUMES_QTD" => "1",
            "DOCUMENT_FRETE_VOLUMES_SPECIES" => "CAIXA",
            "DOCUMENT_FRETE_VOLUMES_NET_WEIGHT" => "10.500",
            "DOCUMENT_FRETE_VOLUMES_GROSS_WEIGHT" => "12.000",
        ),
    ),
    "EXTERNAL_ID" => "89678678",        
    "SALE_ID" => "127654",    
    "DOCUMENT_ISSUE_DATE" => '2021-10-29 18:01:39',       
    "LOGISTICS" => "5a5a165d8385feebec5a21eebd85fc2b",    
    "FREIGHT_MODE" => "SERVICE_SEDEX_CONTRATO_AGENCIA",    
    "FREIGHT_QUOTE" => "1",        
    "DOCUMENT_ATTACHMENT" => "https://app.notazz.com/contrato-de-licenca-notazz.pdf",    
    "REQUEST_ORIGIN" => 'DROP EXPRESS'        
));

$retorno = send_data($fields);
?>  