<?php

require_once (dirname(__FILE__) . '/../../includes/config.php');
session_name(SESSION_NAME);
session_start();
$signup_page = true;

if (!(isset($_SESSION['UserID']))) {
    header('Location: ' . SERVER_URI . '/login');
    exit;
}

else {
    $get_user_terms_status = $conn->prepare('SELECT user_terms_accepted FROM users WHERE user__id = :user__id LIMIT 1');
    $get_user_terms_status->execute(array('user__id' => $_SESSION['UserID']));

    $user_terms_accept = $get_user_terms_status->fetch();

    if ($user_terms_accept[0] == 'true'){
        header('Location: ' . SERVER_URI . '/pedidos/dashboard/');
    }

}

$user_terms_page = true;
$page_title =  "Termos e Condições Gerais para Assinantes";
require_once (dirname(__FILE__) . '/../../includes/layout/fullwidth/fullwidth-header.php');

?>

<div class="container-fluid">
	<div class="page-titles">

	</div>
	<div class="row">
		<div class="col-xl-12" style="max-width: 1000px;margin: 0 auto; height: 92vh;">
			<div class="card">
				<div class="card-header text-center d-block" style="max-width: 600px; margin: 0 auto;">
					<h4 class="card-title">Termos e Condições Gerais para Assinantes</h4>
					<p class="mb-0 subtitle">Para usar os serviços do Logzz, todos os usuários precisam estar de acordo com os Termos e Condições Gerais para Assinantesda plataforma.</p>
        		</div>
				<div class="card-body" style="overflow-x: hidden; overflow-y: scroll; padding: 2.5rem;">
                    <p class="terms">A Logzz oferece uma plataforma tecnológica que permite a contratação de serviços de transporte, logística, entrega de produtos, entre outros, prestados por terceiros, provedores independentes desses serviços. A Logzz não é fornecedora de bens, não presta serviços de transporte ou logística e não atua como transportadora. Os serviços contratados por meio da plataforma Logzz para Empresas são prestados por prestadores terceiros independentes, que não são empregados, prepostos ou representantes da Logzz ou de qualquer de suas Afiliadas.</p>

                    <p class="terms">Estes Termos e Condições Gerais para Assinantes (os "Termos Gerais") regulam a relação entre o assinante identificado no processo de cadastro ou na página de assinatura (o "Assinante") e BBX Cursos Digitais Ltda, pessoa jurídica de direito privado, com sede na Avenida C-4, 931, 15º andar, Sala 2103 B, CEP 74265-040, Jardim América, no município de Goiânia/GO, inscrita no CNPJ sob o nº. 40.892.919/0001-51 (“BBX Cursos Digitais Ltda”).</p>
                    
                    <h4 class="terms mt-2"><b>1. </b>Aplicação dos Termos Gerais e dos Adendos de Planos.</h4>
                    
                    <p class="terms">Estes Termos Gerais estabelecem as condições sob as quais o Assinante criará e utilizará sua Conta junto à Logzz para Assinantes, terá acesso ao Painel de Controle (definido mais adiante) e poderá utilizar um dos planos Logzz para Assinantes. Além destes Termos Gerais, aplicam-se à relação entre a Logzz e o Assinante documentos específicos que regulam cada um dos Produtos.</p>

                    <p class="terms">Os Termos Gerais e os Adendos de planos poderão ser modificados ou atualizados a qualquer momento pela Logzz, mediante prévia notificação ao Assinante (por e-mail ou por meio do Painel de Controle), com antecedência mínima de 15 (quinze) dias. Os documentos atualizados passarão a viger depois do prazo informado na notificação, e a versão atualizada destes Termos Gerais e/ou do Adendo de Produto aplicável será publicada no site da Logzz.</p>

                    <p class="terms">Ao ser notificada de uma alteração nestes Termos Gerais ou nos respectivos Adendos de planos, o Assinante deverá revisar as modificações no prazo estabelecido na notificação. Caso discorde das alterações, o Assinante poderá encerrar sua Conta, sem qualquer multa ou ônus. A continuidade do uso da Conta ou qualquer Produto após tais modificações ou atualizações implica o aceite dos novos termos pelo Assinante. O Assinante deve manter atualizada as suas informações de contato no Painel de Controle.</p>

                    <p class="terms">As palavras grafadas em maiúsculas têm o significado a elas atribuído ao longo destes Termos Gerais ou nos Adendos de Produto. Um glossário de termos definidos encontra-se disponível no fim deste documento.</p>
                    
                    <h4 class="terms mt-2"><b>2. </b>Termos específicos dos planos Logzz para Assinantes.</h4>
                    
                    <p class="terms indent-1"><b>2.1. </b>O Assinante poderá optar por utilizar um ou mais dos seguintes planos da Logzz sujeitos à disponibilidade local: Plano Bronze, Plano Prata e Plano Ouro. O Assinante poderá optar por utilizar um dos planos ao criar uma Conta. Embora os termos aplicáveis a todos os planos (cada um, um "Adendo de Produto") sejam aceitos pelo Assinante neste ato, caso o Assinante não use qualquer dos planos disponibilizados por meio do Painel de Controle, os termos do respectivo Adendo de Produto não se aplicarão.</p>

                    <p class="terms indent-1">Qualquer Adendo de planos aceito pelo Assinante é automaticamente incorporado à relação contratual entre a Logzz e o Assinante. Estes Termos Gerais e quaisquer Adendo de planos são denominados, em conjunto, de “Contrato”.</p>

                    <h4 class="terms mt-2"><b>3. </b>Prazo de Vigência e Rescisão do Contrato.</h4>

                    <p class="terms indent-1"><b>3.1. </b>Este Contrato terá início após o seu aceite pelo Assinante e permanecerá vigente por prazo indeterminado ("Vigência"), podendo ser rescindido de acordo com as condições aqui estabelecidas.</p>

                    <p class="terms indent-1"><b>3.2. </b>Qualquer uma das partes poderá rescindir este Contrato ou qualquer Adendo de Produto, com ou sem motivo, mediante aviso prévio por escrito de 30 (trinta) dias à outra parte. A rescisão do Contrato é uma prerrogativa das partes, não ensejando o pagamento de multa ou indenização (exceto pelos serviços já efetivamente prestados e não pagos).</p>

                    <p class="terms indent-1"><b>3.3. </b>A rescisão de um Adendo de Produto não implica a rescisão de outros Adendos de Produto que se encontrem em vigor no momento da rescisão. Os Adendos de Produto serão automaticamente rescindidos mediante a rescisão destes Termos Gerais.</p>
                    
                    <h4 class="terms mt-2"><b>4. Administração da Conta.</b></h4>
                    
                    <p class="terms indent-1"><b>4.1. Uso do Painel de Controle.</b> Após a assinatura ou aceite deste Contrato, a Logzz criará uma Conta para o Assinante, o que permitirá que o Assinante acesse o navegador online (“Painel de Controle”). Por meio do Painel de Controle, o Assinante terá acesso aos planos que concordou em utilizar por meio dos Adendos de Produto. A Logzz poderá contatar o Assinante por meio de qualquer representante designado por ela como administrador através do Painel de Controle ("Administrador"). O Painel de Controle permitirá que o Assinante: (a) visualize os Produtos que concordou em utilizar ao celebrar os respectivos Adendos de Produto; (b) visualize informações detalhadas de viagens ou outras informações relativas aos planos, que podem incluir, a depender do Produto utilizado, o nome dos Usuários Autorizados, o status, o endereço de origem e destino, o valor da viagem ou pedido, os itens inclusos no pedido de entrega, o ID da viagem ou pedido, a Cobrança de Usuário e o recibo de despesas (“Dados do Painel de Controle”); (c) elabore e acesse relatórios gerados a partir dos Dados do Painel de Controle, (d) gerencie e atualize o cartão de crédito cadastrado (quando aplicável), (e) revise e gerencie as demonstrações de pagamento, (f) liquide saldos pendentes na Conta, além de outras funcionalidades descritas nos Adendos de planos. A Logzz se reserva o direito de adicionar, remover e atualizar recursos e funcionalidades do Painel de Controle a qualquer momento.</p>

                    <p class="terms indent-1"><b>4.2. Administração.</b> O Assinante poderá nomear Administradores adicionais, a seu critério. O Assinante concorda em: (a) manter as credenciais usadas para login no Painel de Controle em sigilo, (b) assegurar que apenas os Administradores autorizados acessem o Painel de Controle e (c) atualizar, conforme necessário, todas as informações do Administrador principal e de outros Administradores autorizados, garantindo que essas informações sejam, a todo tempo, atuais, precisas e completas. O Assinante é responsável por todas as atividades realizadas no Painel de Controle mediante a utilização de suas credenciais de acesso.</p>

                    <p class="terms indent-1"><b>4.3. Atualizações de Usuários Autorizados e Administradores.</b> É de responsabilidade exclusiva do Assinante manter atualizada uma lista dos Usuários Autorizados e dos Administradores que tenham autorização para utilizar cada Produto, incorrendo, assim, nos respectivos custos. A Logzz poderá revisar periodicamente a lista de Usuários Autorizados e Administradores, com vistas a assegurar o cumprimento deste Contrato e para fins de manutenção e suporte. Esta revisão poderá incluir a exclusão de Usuários Autorizados e Administradores que não atendam às condições aqui estabelecidas. </p>

                    <p class="terms indent-1"><b>4.4 Responsabilidade por Atividades do Usuário. </b>O Assinante concorda que: (a) é responsável por todas as Cobranças de Usuário incorridas por Usuários Autorizados e Administradores por meio da Conta, conforme previsto no item 4.3 acima, incluindo todas as Cobranças de Usuário decorrentes de atividades fraudulentas ou outras atividades não permitidas pele Assinante realizadas por um Usuário Autorizado ou Administrador durante o uso da Conta, e (b) as Cobranças de Usuário estão sujeitas a alterações de preço, incluindo (mas sem se limitar) aumentos ocasionais durante períodos de alta demanda, conforme descrito nos Termos de Usuário Final.</p>
                    
                    <p class="terms indent-2"><b>4.4.1 Exclusão de Usuário Autorizado ou Administrador. </b> A exclusão de um Usuário Autorizado ou Administrador da Conta do Assinante deverá ser feita pelo próprio Assinante por meio do Painel de Controle. O Assinante deve informar a Logzz imediatamente caso identifique atividades fraudulentas ou não permitidas por parte de um Usuário Autorizado ou Administrador na sua Conta. Até que este Usuário Autorizado ou Administrador seja removido da Conta pelo próprio Assinante, por meio do Painel de Controle, o Assinante será responsável pelas Cobranças de Usuário referentes às solicitações feitas por tal Usuário Autorizado ou Administrador.</p>

                    <p class="terms indent-1"><b>4.5 Restrições. </b> O Assinante concorda em usar a Conta e o Painel de Controle somente conforme estabelecido neste Contrato. O Assinante não fará e não autorizará nenhum terceiro a: (a) descompilar, desmontar, fazer engenharia reversa e nem de qualquer outro modo tentar derivar o código-fonte ou tecnologia subjacente, metodologias ou algoritmos do Painel de Controle, Serviço Logzz ou Aplicativo, (b) sublicenciar, arrendar, locar, vender, ceder ou de qualquer outra forma transferir, ou prestar o Serviço Logzz ou Aplicativo para qualquer terceiro que não seja um cliente seu, (c) superfaturar, aumentar ou modificar de qualquer outra forma as Cobranças de Usuário por qualquer uso do Serviço ou (d) impor quaisquer taxas ou encargos adicionais a um Usuário Autorizado referente ao uso do Painel de Controle ou do Serviço. A Logzz se reserva todos os direitos que não tenham sido expressamente concedidos ao Assinante ou a terceiros, incluindo Usuários Autorizados, nos termos deste Contrato.</p>

                    <h4 class="terms mt-2"><b>5. </b>Valores e Cobrança </h4>
                    <p class="terms indent-1"><b>5.1 Cobranças de Usuário e Taxas de Serviço. </b>As Cobranças de Usuário e as Taxas de Serviço aplicáveis a cada Produto serão estabelecidas no Adendo de Produto aplicável.</p>
                    <p class="terms indent-2">5.1.1 O valor da Taxa de Serviço, ou sua isenção por um determinado período, será estabelecido durante a criação da Conta ou de outra forma acordado pelas partes. A Taxa de Serviço, quando aplicável, deverá ser paga do mesmo modo da Cobrança de Usuário, ou de outra forma acordada por escrito entre as Partes;</p>
                    <p class="terms indent-1">5.2 Opções de Cobrança</p>
                    <p class="terms indent-2">5.2.1 Suspensão da Conta. A Logzz poderá suspender o acesso ao Painel de Controle pelo Assinante e o acesso ao Perfil de todos os Usuários Autorizados em caso de não pagamento das Taxas de Serviço ou das Cobranças de Usuário devidas pelo Assinante. A suspensão independe de aviso prévio, embora a Logzz se comprometa a envidar melhores esforços para avisar o Assinante sobre valores em atraso e sobre a possibilidade de suspensão dos serviços. Após o pagamento dos valores em atraso, a Logzz poderá, a seu critério, reestabelecer o acesso do Assinante à Conta.</p>
                    <p class="terms indent-2">5.2.2 Se o Assinante não participar do sistema de Cobrança, as Cobranças de Usuário e as Taxas de Serviço serão pagas de acordo com a forma prevista no Adendo de Produto aplicável.</p>
                    <p class="terms indent-1">5.3 Tributos. Todos os pagamentos serão processados na moeda local, exceto nos casos em que as transações estrangeiras tiverem que ser processadas em dólares dos Estados Unidos. Nenhum pagamento é reembolsável, exceto conforme expressamente previsto neste documento. Cada parte será responsável por seus custos e despesas relacionadas à implementação e cumprimento deste Contrato.</p>
                    <h4 class="terms mt-2"><b>6. </b>Propriedade Intelectual</h4>
                    <p class="terms indent-1">6.1 Vedação de Desenvolvimento Tecnológico. As partes concordam que este Contrato não inclui o desenvolvimento de tecnologia, conteúdo, mídia ou outra propriedade intelectual por uma das partes para a outra. Qualquer atividade de desenvolvimento relacionada a tecnologia, conteúdo, mídia ou outra propriedade intelectual deve ser objeto de um novo contrato por escrito entre a Logzz e o Assinante antes do início das atividades.</p>
                    <p class="terms indent-1">6.2 Propriedade. A Logzz é e permanecerá proprietária dos direitos sobre o Painel de Controle, Serviço e Aplicativo, incluindo as atualizações, aprimoramentos e novas versões destes, e sobre toda a informação e documentação disponibilizada para o Assinante ou para qualquer Usuário Autorizado (ou potencial Usuário Autorizado) em conexão com este Contrato.</p>
                    <p class="terms indent-1">6.3 Proibição de Publicidade. Exceto conforme expressamente previsto neste Contrato, nenhuma das partes poderá usar ou fazer referência ao nome, logotipo, marcas registradas ou marcas de serviço da outra parte em um comunicado à imprensa ou, outro tipo de divulgação pública, sem o prévio consentimento da outra parte.</p>
                    <h4 class="terms mt-2"><b>7. </b>Confidencialidade.</h4>
                    <p class="terms indent-1">7.1 O termo “Informação Confidencial” significa qualquer informação confidencial técnica, financeira ou própria do negócio, ou materiais de uma parte;</p>
                    <p class="terms indent-1">7.2 A Parte Receptora concorda que: (a) somente usará Informações Confidenciais para as finalidades permitidas nos termos deste Contrato e (b) não divulgará as Informações Confidenciais a terceiros que não sejam funcionários ou agentes da Parte Receptora que estejam vinculados por obrigações de confidencialidade e uso restrito, pelo menos tão rigorosos quanto os aqui contidos.</p>
                    <p class="terms indent-1">7.3 No caso de a Parte Receptora receber uma intimação, ordem judicial ou administrativa ou qualquer outro pedido de divulgação de qualquer Informação Confidencial da Parte Divulgadora feito por autoridade competente, a Parte Receptora notificará imediatamente a Parte Divulgadora sobre tal intimação, ordem ou solicitação e permitirá que a Parte Divulgadora promova quaisquer defesas possíveis contra a divulgação, caso seja de seu interesse.</p>
                    <p class="terms indent-1">7.4 A Parte Receptora protegerá as Informações Confidenciais da Parte Divulgadora da mesma maneira que protege suas próprias informações de negócio e confidenciais.</p>
                    <h4 class="terms mt-2"><b>8. </b>Privacidade e Segurança de Dados.</h4>
                    <p class="terms indent-1">8.1 Definições. “Dados Pessoais do Assinante” significam: (i) nome completo, (ii) endereço de e-mail sob o domínio do Assinante (ex: nome@empresa.com.br), e (iii) demais informações mutuamente acordadas entre as Partes de um Usuário Autorizado fornecidos pelo Assinante à Logzz, em conexão com este Contrato, com exceção dos dados fornecidos pelo Usuário Autorizado diretamente à Logzz. “Dados Pessoais da Logzz” significam quaisquer dados pessoais de um Usuário Autorizado ou de entregadores contratantes independentes dos quais a Logzz é controladora e que a Logzz compartilha com o Assinante em conexão com este Contrato, incluindo dados pessoais de Usuários Autorizados e de motoristas e entregadores parceiros que integram os Dados do Painel de Controle.</p>
                    <p class="terms indent-1">8.2 Tratamento de dados pelo Assinante. O Assinante é responsável por: (i) obter o consentimento, quando necessário, ou cumprir com qualquer outra obrigação legal para fornecer legitimamente à Logzz os Dados Pessoais do Assinante; (ii) tratar os Dados Pessoais da Logzz apenas para o propósito específico e legítimo de execução das atividades descritas em e/ou relacionadas com este Contrato; (iii) limitar o acesso aos Dados Pessoais da Logzz e aos Dados do Painel de Controle apenas a quem tenha necessidade comercial legítima para acessar tais dados; e (iv) não divulgar Dados Pessoais da Logzz a terceiros, a menos que expressamente autorizado pela Logzz por escrito.</p>
                    <p class="terms indent-1">8.3 Tratamento de dados pela Logzz. A coleta e o tratamento de Dados Pessoais da Logzz, incluindo os dados que a Logzz obtém diretamente de Usuários Autorizados, serão feitos de acordo com a Política de Privacidade da Logzz. A Logzz concorda que (i) só utilizará os Dados Pessoais do Assinante para os fins descritos neste Contrato, (ii) limitará o acesso aos Dados Pessoais do Assinante apenas a quem tenha necessidade comercial legítima para acessar tais dados; e (iiii) não divulgará Dados Pessoais do Assinante a terceiros, a menos que expressamente autorizado pelo Assinante.</p>
                    <p class="terms indent-1">8.4 Papéis das Partes. Cada Parte é um controlador independente dos Dados Pessoais da Logzz e dos Dados Pessoais do Assinante para os fins deste Contrato.</p>
                    <p class="terms indent-1">8.5 Conformidade com a Lei de Proteção de Dados. Cada Parte deverá cumprir com as obrigações a ela aplicáveis dispostas na Lei de Proteção de Dados, em decorrência do tratamento de Dados Pessoais.</p>
                    <p class="terms indent-1">8.6 Segurança. As Partes implementarão medidas técnicas, físicas e organizacionais apropriadas para proteger os Dados Pessoais da outra Parte contra o tratamento não autorizado ou ilegal e contra perda, destruição, dano, alteração ou divulgação não autorizados, bem como qualquer violação de suas medidas de segurança (“Incidente de Segurança da Informação”).</p>
                    <p class="terms indent-1">8.7 Notificação. Cada Parte deverá notificar imediatamente a outra caso tome conhecimento ou tenha motivos para acreditar que ocorreu um Incidente de Segurança da Informação. Esta notificação deverá incluir, pelo menos: (1) a natureza da violação das medidas de segurança; (2) os dados pessoais e os sujeitos de dados potencialmente atingidos; (3) a duração e as consequências esperadas do Incidente de Segurança da Informação; e (4) quaisquer medidas de mitigação ou remediação tomadas ou planejadas em resposta ao Incidente de Segurança da Informação. Após qualquer descoberta, a Parte deverá: (a) tomar todas as medidas razoáveis ​​para investigar, remediar e mitigar os efeitos do Incidente de Segurança da Informação, e (b) fornecer à outras garantias razoavelmente satisfatórias de que tal Incidente de Segurança da Informação não ocorrerá novamente.</p>
                    <p class="terms indent-1">8.8 Transferências de Dados. O Assinante não poderá tratar Dados Pessoais de um titular localizado no Espaço Econômico Europeu ("EEE") em conexão com este Contrato. No caso de o Assinante assim proceder e tratar ou transferir esses Dados Pessoais para fora do EEE, as Partes deverão antes celebrar as Cláusulas Contratuais Padrão aplicáveis. (o que é isso?) – Trata-se de cláusula autorizadora para negociação com empresas que estejam vinculadas à GDPR (LEI DE PROTEÇÃO DE DADOS DA UNIÃO EUROPEIA) sem tais termos não pode haver comercialização com esses países, caso não tenha interesse em comercializar com clientes de tais países, retiramos.</p>
                    <h4 class="terms mt-2"><b>9. </b>Declarações e Garantias.</h4>
                    <p class="terms indent-1">9.1 Declarações Mútuas. Cada parte declara e garante que: (a) tem plenos poderes e autoridade para firmar este Contrato e cumprir as obrigações aqui descritas, (b) o aceite e a execução deste Contrato não violam e não violarão nenhum outro Contrato que essa parte tenha firmado, e (c) está devidamente estabelecida, validamente existente e encontra-se em situação regular nos termos das leis da jurisdição de sua origem; (d) as Marcas licenciadas nos termos deste Contrato não infringem nem violam direitos de terceiros; (e) não é uma entidade governamental ou de economia mista, ou de outra forma detida, controlada ou criada por uma entidade governamental.</p>
                    <p class="terms indent-1">9.2 Garantias sobre os Produtos. A Logzz fornece o Serviço, o Aplicativo e o Painel de Controle "da forma como estão disponíveis no momento" e sem garantias de funcionamento ou de adequação às necessidades específicas do Assinante. O Assinante está ciente que o Serviço, o Aplicativo e o Painel de Controle poderão apresentar falhas ou interrupções de disponibilidade.</p>
                    <p class="terms indent-1">9.3 Natureza do Serviço Logzz. O Assinante reconhece e concorda que o Serviço é uma plataforma de tecnologia que permite solicitar serviços de transporte terrestre, logística e entregas sob demanda, prestados por contratantes independentes. A Logzz não é um prestador de serviços de transporte, logística ou entrega. A Logzz não garante a disponibilidade de serviços de transporte, logística ou entrega, a pontualidade das chegadas ou partidas ou das entregas, ou qualquer outro nível de serviço relacionado aos contratantes independentes que possam ser contratados por meio do Serviço.</p>
                    <h4 class="terms mt-2"><b>10. </b>Indenização</h4>
                    <p class="terms indent-1">10.1 Uma Parte (a “Parte Indenizadora”) indenizará, defenderá e isentará a outra Parte (a “Parte Indenizada”), suas Afiliadas e seus respectivos conselheiros, diretores, funcionários, agentes, sucessores e cessionários contra todas as reclamações, danos, perdas e despesas (incluindo honorários advocatícios externos razoáveis) com relação a qualquer reclamação de terceiros decorrente de ou relacionada a: (a) uma violação de quaisquer declarações ou garantias da Parte Indenizadora neste Contrato ou qualquer Adendo de Produto; (b) uma violação das obrigações estabelecidas nas cláusulas de Privacidade e Segurança de Dados da Parte Indenizadora neste Contrato ou qualquer Adendo de Produto; ou (c) uma violação de direitos de propriedade intelectual de um terceiro pelas Marcas da Parte Indenizadora, mas somente se tais Marcas tiverem sido usadas pela Parte Indenizada na forma aprovada pela Parte Indenizadora.</p>
                    <p class="terms indent-1">10.2 A Parte Indenizada notificará prontamente a Parte Indenizadora acerca de qualquer reclamação potencial sujeita a indenização nos termos desta Cláusula. A Parte Indenizadora assumirá a defesa da reclamação através de um advogado por ela designado. A Parte Indenizadora não fará acordos, nem prejudicará qualquer defesa, sem o consentimento por escrito da Parte Indenizada, que não será retido injustificadamente. A Parte Indenizada cooperará razoavelmente com a Parte Indenizadora na defesa de uma reclamação, às custas da Parte Indenizadora.</p>
                    <h4 class="terms mt-2"><b>11. </b>Limitação de Responsabilidade</h4>
                    <p class="terms indent-1">11.1 As Partes respondem exclusivamente pelos danos emergentes e diretos que vierem a causar no âmbito deste Contrato. Nenhuma das Partes responderá por lucros cessantes ou outros danos intangíveis, indiretos ou imateriais.</p>
                    <p class="terms indent-1">11.2 O valor de responsabilidade se aplica a danos decorrentes de: (a) falsidade das declarações e garantias prestadas neste Contrato, por qualquer das partes; (b) violação das obrigações estabelecidas na Cláusula 8.2 destes Termos Gerais; (c) violação de propriedade intelectual de terceiros relativa ao uso das Marcas; e (d) quebra das obrigações de confidencialidade previstas neste Contrato.</p>
                    <p class="terms indent-1">11.3 A Logzz se compromete a indenizar o Assinante por problemas relativos exclusivamente a furtos e avarias dos produtos remetidos através da plataforma, tendo como termo ao início da responsabilidade o momento em que a mercadoria encontrar-se sob posse do prestador de serviços representante da Logzz, desde que a mercadoria tenha sido encaminhada com nota fiscal de simples remessa.</p>
                    <p class="terms indent-2">11.3.1 O valor de indenização constante da clausula 11.3 será correspondente ao valor de custo do produto avariado ou objeto de furto inserido em nota fiscal, multiplicado pela quantidade de produtos extraviado/avariado.</p>
                    <p class="terms indent-1">11.4 Em que pese as partes atuarem sem qualquer exclusividade resta vedado ao Assinante sob pena de incurso em penalidades pela prática de concorrência desleal, cooptar, contatar, sondar, indicar, ajustar (verbal ou contratualmente), fornecer ou realizar qualquer contratação direta com os prestadores de serviços parceiros da Logzz pelo período dos últimos 12 (doze) meses, permanecendo tal vedação pelo período de 60 (sessenta) meses subsequentes ao término do presente contrato.</p>
                    <p class="terms indent-1">11.5 Em caso de descumprimento a qualquer momento do disposto na clausula 11.4 o Assinante pagará a Logzz a título de indenização o valor de R$ 150.000,00 (cento e cinquenta mil reais) por contratação realizada, devidamente cumulados com juros legais e correção monetária além de custas e eventuais honorários advocatícios para ingresso com a respectiva ação judicial.</p>
                    <h4 class="terms mt-2"><b>12. </b>Disposições Gerais</h4>
                    <p class="terms indent-1">12.1 Este Contrato é regido pela lei brasileira. Em caso de litígio, as partes concordam em submeter a controvérsia exclusivamente ao foro central da Comarca de Goiânia/GO.</p>
                    <p class="terms indent-1">12.2 Qualquer aviso ou comunicação ao Assinante será enviado por email ao(s) Administrador(es) cadastrado(s) no Painel de Controle. Qualquer aviso ou comunicação à Logzz que seja de natureza legal/contratual deve ser enviado ao e-mail ____________.</p>
                    <p class="terms indent-1">12.3 A falha de qualquer uma das Partes em fazer cumprir, a qualquer momento, ou por qualquer período, as disposições deste Contrato, ou a falha de qualquer uma das Partes em exercer qualquer direito aqui previsto, não deve ser interpretada como uma renúncia a tal disposição ou direito e não afetará o direito dessa parte de fazer cumprir tais disposições ou exercer tais direitos.</p>
                    <p class="terms indent-1">12.4 Caso qualquer cláusula deste Contrato seja considerada inválida ou inexequível por decisão transitada em julgado por um tribunal competente, o restante deste Contrato (e cada um dos demais termos e condições aqui contidos) permanecerá válido e exequível.</p>
                    <p class="terms indent-1">12.5 As Partes não respondem pelo atraso ou descumprimento deste Contrato em casos fortuitos ou de força maior.</p>
                    <p class="terms indent-1">12.6 Este Contrato (incluindo os Termos Gerais e os Adendos de Produto) não pode ser cedido, no todo ou em parte, por uma Parte sem o consentimento prévio e por escrito da outra parte. As Partes podem ceder este contrato, mediante simples notificação: a) para um Afiliada, ou b) em conexão com a venda total ou substancial de participação ou dos ativos. Sujeito ao disposto acima, este Contrato vincula cada uma das Partes e seus sucessores e cessionários.</p>
                    <p class="terms indent-1">12.7 Este Contrato não estabelece entre as partes, seus prepostos, empregados e contratados, qualquer forma de sociedade, associação, mandato, representação, joint venture, agência, consórcio, responsabilidade solidária e/ou subsidiária ou qualquer vínculo trabalhista, e nenhuma das partes tem o direito de celebrar contratos, vincular legalmente, incorrer em dívida ou de outra forma assumir qualquer responsabilidade ou obrigação em nome da outra Parte.</p>
                    <p class="terms indent-1">12.8 Cada Parte é responsável pelo adimplemento das obrigações que a legislação fiscal lhes atribuir no que diz respeito ao objeto destes Termos Gerais e de qualquer Adendo de Produto.</p>
                    <p class="terms indent-1">12.9 As Partes comprometem-se a, no âmbito deste Contrato, cumprir as leis anticorrupção aplicáveis, incluindo, sem limitação, a Lei nº 12.846/2013. As Partes se absterão de pagar, mandar pagar, oferecer ou prometer pagamento ou presentes de valor, direta ou indiretamente, a qualquer pessoa ou empresa, incluindo, sem limitação, funcionários públicos, candidatos a cargos públicos ou colaboradores das Partes, com o objetivo de induzir ou recompensar qualquer ato relacionado a este Contrato ou aos negócios entre as Partes. Cada Parte se compromete a notificar a outra Parte acerca de qualquer violação ou potencial violação de qualquer lei anticorrupção que guarde relação direta ou indireta com este Contrato ou com os negócios entre as Partes. As Partes cooperarão de boa-fé para investigar eventual violação. Caso qualquer das partes tenha políticas internas que especifiquem valores máximos para brindes ou entretenimento, é responsabilidade desta Parte informar a outra por escrito (na forma de notificação formal estabelecida neste Contrato) para que seja vinculante.</p>
                    
				</div>
                <div class="card-footer">
                    <form id="UserTermsAccept">
                    <div class="col-sm-8 text-center" style="display: block; margin: 0 auto;">
                        <div class="custom-control custom-checkbox mb-3 checkbox-success" style="font-size: 1 em">
                            <input type="checkbox" class="custom-control-input" name="aceito-os-termos" id="aceito-os-termos">
                            <label class="custom-control-label" for="aceito-os-termos" style="margin-top: 0.8em"> Afirmo que <b>li e aceito</b> os Termos e Condições Gerais para Assinantes da plataforma Logzz.</label>
                        </div>
                        
                    </div>
                    <div class="col-md-4 text-center mt-2" style="display: block; margin: 0 auto;">
                        <button type="submit" class="btn btn-success btn-block">Prosseguir</button>
                    </div>
                    </form>
                </div>
			</div>
		</div>
	</div>
</div>

<?php
	require_once (dirname(__FILE__) . '/../../includes/layout/fullwidth/fullwidth-footer.php');
?>
	